name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main   # main branch'e push yapıldığında tetiklenir

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo'yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js kur
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Bağımlılıkları yükle
      - name: Install dependencies
        run: npm install

      # 4. React app'i build et
      - name: Build
        run: npm run build

      # 5. Deploy işlemi
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}  # burada GH_PAT secret'ını kullanıyoruz
          publish_dir: ./build               # React build sonucu oluşan dizin
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
